# Generated by Django 4.2.3 on 2023-08-01 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_expensetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='exp_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.expensetype'),
            preserve_default=False,
        ),
    ]
